package:
  name: menpo
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.10,<1.11
    - cython 0.23.*

  run:
    - python
    - pathlib 1.0  # [py2k]

    # Scientific Python Stack
    - numpy >=1.10,<1.11
    - scipy 0.16.*
    - pillow  2.9.*

    # Features
    - cyvlfeat 0.4.*

    # Visualization
    - matplotlib 1.4.*
    - menpowidgets 0.1.*

    # Test dependencies
    - mock 1.0.1
    - nose

test:
  requires:
    - coverage

  imports:
    - menpo

about:
  home: https://github.com/menpo/menpo/
  license: BSD
